### ISSUE TITLE
Tests doesn't work (neither CI) because bean "doesn't" exist

### ISSUE THREAD

**Issue by opueyociutad** [iksopo/urlshortener#5]
Running the project seems to work fine locally, but when trying to execute tests, it fails and the following error appears in the report:
```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'es.unizar.urlshortener.core.usecases.ValidateURIUseCase' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1790)
```

However, the bean exists.

To recreate it, just run `./gradlew check`. If you want to run the app to check if it works run `./gradlew bootRun`.

**Comment by opueyociutad** [comment]
@fjlopez

**Comment by fjlopez** [comment]
@iksopo I need to know in which branch happens this problem.

**Comment by opueyociutad** [comment]
@fjlopez It happens in almost all of them (I would say all), but I suggest trying with the master one, since it is the simplest.

**Comment by fjlopez** [comment]
@iksopo, This is solved. Your declaration was:
```kotlin
@WebMvcTest
@ContextConfiguration(classes = [
    UrlShortenerControllerImpl::class,
    RestResponseEntityExceptionHandler::class
])
```
but the dependencies required were:

```kotlin
@WebMvcTest
@ContextConfiguration(classes = [
    UrlShortenerControllerImpl::class,                  // ValidateURIUseCase is not mocked
    ValidateURIUseCaseImpl::class,                      // (was missing) Depends on RestTemplate
    RestTemplate::class,                                         // (was missing)
    RestResponseEntityExceptionHandler::class // Handles all the exceptions
])
```
Add the dependencies when the system claims that a bean is missing.  Nevertheless, in this specific case I think that you should mock `ValidateURICase`.

**Comment by opueyociutad** [comment]
Thanks! I will try that if I have enough time.
